server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: ${API_GATEWAY_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
    org.springframework.cloud.gateway: info