server:
  port: ${DISCOVERY_SERVICE_PORT}

spring:
  application:
    name: ${DISCOVERY_SERVICE_NAME}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  info:
    java:
      enabled: true
    env:
      enabled: true

logging:
  level:
    org.springframework: info
