server:
  port: ${API_URL_SHORTENER_PORT}

spring:
  application:
    name: ${API_URL_SHORTENER_NAME}
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
